export const NAV_ITEMS = [
  { href: "/dashboard", label: "Dashboard" },
  { href: "/pipeline", label: "Pipeline" },
  { href: "/ceo", label: "CEO" },
  { href: "/research", label: "Research" },
  { href: "/sourcing", label: "Sourcing" },
  { href: "/economics", label: "Economics" },
  { href: "/legal", label: "Legal" },
  { href: "/ecommerce", label: "Ecommerce" },
  { href: "/marketplace", label: "Marketplace" },
  { href: "/marketing", label: "Marketing" },
  { href: "/operations", label: "Operations" },
  { href: "/cfo", label: "CFO" },
  { href: "/projects", label: "Projects" },
  { href: "/agents", label: "Agents" },
  { href: "/approvals", label: "Approvals" },
  { href: "/audit", label: "Audit" },
  { href: "/status", label: "Status" },
] as const;
