"""add objective context

Revision ID: 92bb1c1b1923
Revises: e27fd0a8c326
Create Date: 2026-09-15 23:22:45.742666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bb1c1b1923'
down_revision: Union[str, Sequence[str], None] = 'e27fd0a8c326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objectives', sa.Column('context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objectives', 'context')
    # ### end Alembic commands ###
