"""add correlation id to product analyses

Revision ID: c1ff9cbdd4d3
Revises: d40cea42ad85
Create Date: 2026-09-16 12:30:45.286634

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c1ff9cbdd4d3'
down_revision: str | Sequence[str] | None = 'd40cea42ad85'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_analyses', sa.Column('correlation_id', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_analyses', 'correlation_id')
    # ### end Alembic commands ###
