"""add agent execution log table

Revision ID: d40cea42ad85
Revises: 473eb2bee176
Create Date: 2026-09-16 12:14:16.975052

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd40cea42ad85'
down_revision: str | Sequence[str] | None = '473eb2bee176'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_execution_log',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('capability', sa.String(length=100), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_execution_log')
    # ### end Alembic commands ###
